### ISSUE TITLE
PLEASE A REQUEST: Global Dark Theme (focused on browser performance)

### ISSUE THREAD

**Issue by EstherMoellman** [Psykek66/UserCSS#2]
Hi @Psykek66 , 

At your "Hackmath Night Mode", today I read  your message "I'm taking requests for specific website themes". So, please, I have the following request:

I am a newbie at CSS.
I created this [Global Dark Theme](https://pastebin.com/RuGAdtuW) (GDT).
This work is not focused on perfection, neither on aesthetic details etc.
The main focus here is browser performance (less CPU, RAM etc).
Therefore, in order to gain performance, this GDT is able to paid a price at the aesthetic level.

I already tested this GDT comparing with other GDT at usertyle.org.
I used lot of tools (online and offline).
And I can confirm you, that my GDT until now is the best in browser performance (CPU, RAM etc). 

Also, this GDT may work at any browser through an add-on or extension (Stylus, Stylish etc).
But it works much better at Firefox and userContent.css.

Please, my request to you is to improve my work.
I did this theme with a very basic level of CSS.
And I know that it may be improved.

If I am lucky and you accept my request, this theme is going to be different from other GDT' competitors, because this GDT is going to be the first GDT focused on browser performance.

In exchange for my request to you, I offer the work I did until today (attached above in the pastebin link), and I also offer you my collaboration, in order to help you to improve this GDT.
I am a member of a small club, having 150 members in 8 countries, interested on Firefox' customizations, CSS' codes, JS' scripts etc. And we can help you, for example by testing your work, or by searching something you need, etc.

Of course, if you accept my request, then you can take the full ownership of this GDT, hosting it at your REPO under your name and authorship.

If you can't attend my request, or you don't want, don't have interest etc, please, no problem, I understand, is perfectly fine.
But if by chance you are interested... it will be great!

Thank you in advance, and have a nice day! : )

**Comment by Psykek66** [comment]
Sorry, but honestly, I'm not good enough with CSS to work on global styles. If you want to request anything else, I will look into it, but please request anything else in the discord server: https://discord.gg/9uMWE3U
